-- Our Frame Supabase schema
-- Run this in Supabase Dashboard -> SQL Editor before the first Vercel backend deploy.
-- The FastAPI backend connects directly through DATABASE_URL. The frontend should not
-- read these tables directly through the Supabase Data API.

create table if not exists public.users (
  id integer generated by default as identity primary key,
  email varchar(320) not null unique,
  display_name varchar(200),
  avatar_url varchar(2048),
  auth_provider varchar(50) not null default 'google',
  google_sub varchar(200) unique,
  is_platform_admin boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists ix_users_email on public.users (email);
create index if not exists ix_users_google_sub on public.users (google_sub);

create table if not exists public.user_sessions (
  id integer generated by default as identity primary key,
  session_token varchar(128) not null unique,
  user_id integer not null references public.users (id),
  expires_at timestamptz not null,
  created_at timestamptz not null default now(),
  pending_workspace_id integer
);

create index if not exists ix_user_sessions_session_token on public.user_sessions (session_token);
create index if not exists ix_user_sessions_user_id on public.user_sessions (user_id);

create table if not exists public.workspaces (
  id integer generated by default as identity primary key,
  owner_user_id integer not null references public.users (id),
  name varchar(200) not null,
  slug varchar(100) not null unique,
  subtitle varchar(400),
  layout_preset varchar(50) not null default 'editorial',
  theme_preset varchar(50) not null default 'warm_dark',
  privacy_mode varchar(50) not null default 'private',
  folder_template varchar(50) not null default 'family',
  onboarding_complete boolean not null default false,
  drive_connect_deferred boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists ix_workspaces_owner_user_id on public.workspaces (owner_user_id);
create index if not exists ix_workspaces_slug on public.workspaces (slug);

create table if not exists public.workspace_members (
  id integer generated by default as identity primary key,
  workspace_id integer not null references public.workspaces (id),
  user_id integer not null references public.users (id),
  role varchar(50) not null default 'viewer',
  created_at timestamptz not null default now()
);

create index if not exists ix_workspace_members_workspace_id on public.workspace_members (workspace_id);
create index if not exists ix_workspace_members_user_id on public.workspace_members (user_id);

create table if not exists public.drive_connections (
  id integer generated by default as identity primary key,
  workspace_id integer not null unique references public.workspaces (id),
  user_id integer not null references public.users (id),
  provider varchar(50) not null default 'google',
  google_account_email varchar(320),
  root_folder_id varchar(200),
  encrypted_access_token text,
  encrypted_refresh_token text,
  token_expiry timestamptz,
  connection_status varchar(50) not null default 'pending',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists ix_drive_connections_workspace_id on public.drive_connections (workspace_id);
create index if not exists ix_drive_connections_user_id on public.drive_connections (user_id);

create table if not exists public.albums (
  id text primary key,
  name text not null,
  parent_id text,
  cover_photo_id text,
  photo_count integer,
  child_count integer,
  drive_modified_time timestamptz,
  last_synced timestamptz,
  created_at timestamptz not null default now(),
  excluded boolean not null default false,
  section text
);

create index if not exists ix_albums_parent_id on public.albums (parent_id);
create index if not exists ix_albums_excluded on public.albums (excluded);
create index if not exists ix_albums_section on public.albums (section);

create table if not exists public.photos (
  id text primary key,
  name text not null,
  mime_type text not null,
  parent_folder_id text,
  created_time timestamptz,
  modified_time timestamptz,
  size bigint,
  width integer,
  height integer,
  web_view_link text,
  cached_at timestamptz not null default now()
);

create index if not exists ix_photos_parent_folder_id on public.photos (parent_folder_id);
create index if not exists ix_photos_created_time on public.photos (created_time);

create table if not exists public.favorites (
  id integer generated by default as identity primary key,
  photo_id text not null unique,
  photo_name text not null default '',
  folder_id text,
  favorited_at timestamptz not null default now(),
  note text
);

create index if not exists ix_favorites_photo_id on public.favorites (photo_id);
create index if not exists ix_favorites_folder_id on public.favorites (folder_id);

create table if not exists public.section_mappings (
  id integer generated by default as identity primary key,
  folder_id text not null unique,
  section_key text not null,
  label text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists ix_section_mappings_folder_id on public.section_mappings (folder_id);
create index if not exists ix_section_mappings_section_key on public.section_mappings (section_key);

create table if not exists public.ai_results (
  id integer generated by default as identity primary key,
  photo_id text not null,
  tool_name text not null,
  model text not null,
  input_hash text not null,
  output text not null,
  confidence double precision,
  created_at timestamptz not null default now()
);

create index if not exists ix_ai_results_photo_id on public.ai_results (photo_id);

create table if not exists public.audit_logs (
  id integer generated by default as identity primary key,
  actor_user_id integer references public.users (id),
  workspace_id integer references public.workspaces (id),
  event_type varchar(100) not null,
  event_metadata text,
  created_at timestamptz not null default now()
);

create index if not exists ix_audit_logs_actor_user_id on public.audit_logs (actor_user_id);
create index if not exists ix_audit_logs_workspace_id on public.audit_logs (workspace_id);
create index if not exists ix_audit_logs_event_type on public.audit_logs (event_type);

create table if not exists public.media_items (
  id integer generated by default as identity primary key,
  workspace_id integer references public.workspaces (id),
  drive_file_id varchar(255) not null,
  folder_id varchar(255),
  name varchar(500) not null,
  media_type varchar(20) not null,
  mime_type varchar(100) not null,
  created_time timestamptz,
  modified_time timestamptz,
  size bigint,
  width integer,
  height integer,
  duration_ms integer,
  drive_thumbnail_url text,
  web_view_link text,
  processing_status varchar(30) not null default 'queued',
  processing_error text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint uq_media_items_workspace_drive_file unique (workspace_id, drive_file_id)
);

create index if not exists ix_media_items_workspace_id on public.media_items (workspace_id);
create index if not exists ix_media_items_drive_file_id on public.media_items (drive_file_id);
create index if not exists ix_media_items_folder_id on public.media_items (folder_id);
create index if not exists ix_media_items_media_type on public.media_items (media_type);
create index if not exists ix_media_items_mime_type on public.media_items (mime_type);
create index if not exists ix_media_items_created_time on public.media_items (created_time);
create index if not exists ix_media_items_modified_time on public.media_items (modified_time);
create index if not exists ix_media_items_processing_status on public.media_items (processing_status);

create table if not exists public.media_derivatives (
  id integer generated by default as identity primary key,
  media_item_id integer not null references public.media_items (id),
  kind varchar(50) not null,
  storage_backend varchar(50) not null default 'local',
  storage_key varchar(1000) not null,
  content_type varchar(100) not null,
  width integer,
  height integer,
  size bigint,
  status varchar(30) not null default 'queued',
  error text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint uq_media_derivatives_item_kind unique (media_item_id, kind)
);

create index if not exists ix_media_derivatives_media_item_id on public.media_derivatives (media_item_id);
create index if not exists ix_media_derivatives_kind on public.media_derivatives (kind);
create index if not exists ix_media_derivatives_status on public.media_derivatives (status);

insert into storage.buckets (id, name, public)
values ('our-frame-media-cache', 'our-frame-media-cache', false)
on conflict (id) do nothing;

alter table public.users enable row level security;
alter table public.user_sessions enable row level security;
alter table public.workspaces enable row level security;
alter table public.workspace_members enable row level security;
alter table public.drive_connections enable row level security;
alter table public.albums enable row level security;
alter table public.photos enable row level security;
alter table public.favorites enable row level security;
alter table public.section_mappings enable row level security;
alter table public.ai_results enable row level security;
alter table public.audit_logs enable row level security;
alter table public.media_items enable row level security;
alter table public.media_derivatives enable row level security;
